# nixpacks.toml

[phases.setup]
nixPkgs  = ["flutter"]
aptPkgs  = ["unzip"]

[phases.install]
commands = ["flutter pub get"]

[phases.build]
commands = ["flutter build web --release"]

[serve]
command = "nginx -g 'daemon off;'"
publish = "build/web"
