[phases.setup]
commands = [
  "git submodule update --init --recursive",
  "flutter/bin/flutter config --enable-web"
]

[phases.build]
commands = [
  "flutter/bin/flutter build web --release"
]

[deploy]
startCommand = "npx serve -s build/web -l $PORT"
